### ISSUE TITLE
:not() is being shown as a pseudo-element when it should be a pseudo-class

### ISSUE THREAD

**Issue by sidonaldson** [keeganstreet/specificity#17]
:not() is being shown as a pseudo-element when it should be a pseudo-class.

This is important as a single class cannot override a chain of one or more `.not()`s as each one bumps the specificity by one.

see [http://codepen.io/sidonaldson/pen/PZQwZz]

**Comment by keeganstreet** [comment]
Hi Simon,

The negation pseudo-class is an interesting one, because its specificity is defined by whatever is contained between the brackets. So `:not(.class)` has the same level of specificity as `.class`, `:not(div)` has the same level as `div`, and of course `:not(#id)` would blow them both out of the water.

In your CodePen example, you have used attribute selectors inside the negation pseudo-class. Attribute selectors have the same level of specificity as class selectors, so they are overriding the `.className` rule because there are two of them chained together with an element selector:

![specificity of negation selector](https://cloud.githubusercontent.com/assets/513363/12567309/7a77795e-c412-11e5-88c6-7430fe96c9d3.png)

Cheers,
Keegan

**Comment by sidonaldson** [comment]
Thanks for the detailed reply Keegan, honestly thought I was reporting a bug but alas I completely misunderstood the whole thing. Not entirely sure I agree with the specification but the specificity calculator is correct! Thanks for a great tool

**Comment by keeganstreet** [comment]
My pleasure mate, I am a bit of a specificity geek :)
