### ISSUE TITLE
command line argument that takes a file as argument

### ISSUE THREAD

**Issue by Maxlufs** [keeganstreet/specificity#26]
Hi, I've been looking for an npm package to basically suffix all the rules in my css files with a comment that has the specificity in it, so that i know which rule might override another. I've been using this node script just for myself for a while.

```js
#!/usr/bin/env node
// index.js
var fs = require('fs');
var specificity = require('specificity');
var aArgv = process.argv.slice(2);

fs.readFile(aArgv[0], 'utf8', function(oErr, sData) {
  if (oErr) {
    return console.log(oErr);
  }
  var sResult = sData.replace(/(^|}|\/\*|\/\/)(\s*?)(#|\.|:|\[|[a-zA-Z])(.*?{)/gm, function(match, $1, $2, $3, $4 {
    var sSelector = ($3 + $4).slice(0, -1); // selector, trim last character which is "{"
    var sSpecificity =specificity.calculate(sSelector)[0].specificity; // e.g. 0,0,0,1
    return ($1 + $2 + $3 + $4 + ' /*' + sSpecificity + '*/')
 })
  console.log(sResult)
})
```
```sh
./index.js CSSFILE.css > NEWCSSFILE.css
```
The before and after looks like
```css
p:nth-child(1) {...}
```
=> 
```css
p:nth-child(1) { /*0,0,1,1*/...}
```
Ideally it would be great to have native IDE built-ins or just integrate in the build tool during dev process, but i would hope that it'd be possible to do this task with *specificity*'s built-in command line (other environments too), something like

```sh
specificity -f CSSFILE.css > NEWCSSFILE.css
```

Hope this would be something that you'd consider. If anyone happens to know any lib that does this or something similar or more, I'd be grateful for your sharing.

Thanks.

**Comment by keeganstreet** [comment]
Hi @Maxlufs,

Thanks for sharing your work here. I would suggest that you create this as its own github repo and npm package. It can still include `specificity` as a dependency. I don't want to add file system processes to this package because I want to keep it simple and re-usable across different environments like Node.JS and the web.

You might also like to check out PostCSS, as this might be a good platform for building your tool on. Its really geared around modifying and processing CSS files and you could write a PostCSS extension that inserts the specificity of each selector as a comment. PostCSS will generate an Abstract Syntax Tree of the CSS document, which will allow you to easily find all the selectors without having to use regular expressions.

Cheers,
Keegan
