### ISSUE TITLE
Stacked ID selectors don't affect specificity

### ISSUE THREAD

**Issue by TedYav** [keeganstreet/specificity#34]
I learned a pretty cool thing today at work that I couldn't find much about online. Went to try it out on the specificity calc and got an invalid reading (unless this is just a hack).

Doing #test counts as one ID selector, but doing #test#test counts as two, or is at least more specific. However, in this calculator they both count as 1 ID selector. [Here's a codepen where I was playing around with this.](https://codepen.io/anon/pen/QgaoLL) Cheers!

**Comment by keeganstreet** [comment]
Thanks for letting me know Ted! It's definitely a bug in the calc.
".test.test" works but not "#test#test". I'll fix this up.

On 29 Jun. 2017 5:40 pm, "Ted Yavuzkurt" <notifications@github.com> wrote:

I learned a pretty cool thing today at work that I couldn't find much about
online. Went to try it out on the specificity calc and got an invalid
reading (unless this is just a hack).

Doing #test counts as one ID selector, but doing #test#test counts as two,
or is at least more specific. However, in this calculator they both count
as 1 ID selector. Here's a codepen where I was playing around with this.
<https://codepen.io/anon/pen/QgaoLL> Cheers!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/keeganstreet/specificity/issues/34>, or mute the thread

**Comment by keeganstreet** [comment]
Sorry @TedYav, I have the memory of a goldfish. This issue was fixed recently (#29). I just didn't publish it to npm, or the specificity.keegan.st website. I will do that now.

**Comment by TedYav** [comment]
Hey man sorry for not responding sooner. Also spaced and didn't respond, great! :)
