### ISSUE TITLE
Incorrect calculation when using CSS Modules

### ISSUE THREAD

**Issue by Hypnosphi** [keeganstreet/specificity#40]
`calculate(':global(.a) span:nth-child(2)')` should be `0,0,3,1` but it returns `0,0,2,0`

**Comment by keeganstreet** [comment]
Thanks for the report @Hypnosphi. I'm going to update the calc to filter out `:global` and `:local` scope markers so that the specificity is calculated properly for selectors that use CSS Modules.

Note that `:global(.a) span:nth-child(2)` should return a value of `0,0,2,1`. `:global` is not a pseudo-class, but a scope marker that is read and removed by CSS Modules at compilation time.

**Comment by keeganstreet** [comment]
Fixed in `0.4.1`.

![image](https://user-images.githubusercontent.com/513363/44718461-7ae6d580-ab03-11e8-9ed9-e09d7ef90091.png)
