### ISSUE TITLE
Support for the :where pseudoclass function

### ISSUE THREAD

**Issue by mattxwang** [keeganstreet/specificity#45]
Hi there! Crossposting an issue from https://github.com/stylelint/stylelint/issues/5065 submitted by @jonathantneal.

It seems as if `specificity` doesn't properly support the rules around the `:where()` pseudoclass function. In particular, the spec ref says:

> Unlike `:is()`, neither the `:where()` pseudo-class, nor any of its arguments, contribute to the specificity of the selector—its specificity is always zero.

In contrast, trying this out in the [Specificity Calculator](https://specificity.keegan.st/) or using the library, cases like `:where(hr)` have a nonzero specificity.

(in turn, this has triggered an issue in stylelint's `no-descending-specificity` rule)

I'm not familiar with this package, but more than happy to take a look at what needs to be done!

[MDN ref](https://developer.mozilla.org/en-US/docs/Web/CSS/:where) & [spec ref](https://drafts.csswg.org/selectors-4/#zero-matches) for `:where()`.

**Comment by keeganstreet** [comment]
Hey @mattxwang, this calculator doesn't currently have support for any of the Selectors Level 4 draft spec (including `:where()`). But I can see its supported in Chrome, Firefox and Safari, so it's probably confusing for users. Adding support is going to require quite a re-write though. Currently input is parsed with regular expressions but this won't really cut it because CSS4 selectors can be so complicated. Maybe input should be parsed into something like an abstract syntax tree before calculating the specificity.

**Comment by mattxwang** [comment]
Thanks for the quick response and clarification Keegan! Hm, that does make things tricky. Were you planning on rewriting the package anytime soon (it is a lot of work, and I already appreciate you releasing this as OSS as-is)? If so, it may be something I can help you with; if not, I can discuss this with the Stylelint team and see if there are alternate ways for us to resolve our downstream issue.

**Comment by keeganstreet** [comment]
Hey @mattxwang , I don't have plans to do a rewrite in the immediate future.

**Comment by mattxwang** [comment]
Gotcha, let me update the downstream issue then. Thank you for your help so far!

**Comment by bartveneman** [comment]
I have been using this library for years on projectwallace.com and all underlying projects and has done a terrific job. I'm currently rewriting the complete analyzer using csstree, which creates a beautiful AST and could do the job quite well. Can I help by testing csstree to calculate specificity?

https://github.com/csstree/csstree

**Comment by keeganstreet** [comment]
Hey @bartveneman, the AST generated by csstree looks good. It includes selector details unlike PostCSS's AST. I think that's a good idea. If you would be happy to try it out that would be fantastic.

![image](https://user-images.githubusercontent.com/513363/116168224-4b217d00-a745-11eb-9756-5c51a5557f51.png)

**Comment by bartveneman** [comment]
Well... I had implemented a working version and after some twitter conversations, @lahmatiy went along and added it to cssnano: https://github.com/css/csso/commit/7af7388b5f8e29ce297438caf53ae24ae72c88b3

He also mentioned that he might add it to csstree itself, so perhaps we can wait until that happens, because that would make this library pretty much a one-liner 😁

**Comment by bartveneman** [comment]
I have created a [Proof Of Concept repo using CSSTree](https://github.com/projectwallace/specificity) and it works beautifully. I've copied over the CSSO implementation and tests and put it into a single script. 

I don't intend to keep this PoC repo around because:

1) it's 99% copied from CSSO and not my original work
2) it belongs in your repo, because it'll help the most developers understanding their CSS.

## Todo

- [x] Calculate specificity
- [ ] Show how parts of selector contribte to specificity
- [ ] Implement comparison function

## The way forward

Your call. I'd be happy to help move things forward. Perhaps we should ask @lahmatiy if it's ok to use/modify his code for this repo.

**Comment by keeganstreet** [comment]
Hey, nice work @bartveneman, I think we will need to be driven by the decision in https://github.com/csstree/csstree/issues/158

If csstree calculates specificity, which sounds great, then this library can probably be deprecated as it doesn't support CSS level 4 selectors. If the maintainer of csstree prefers not add specificity logic, then we could update this library to something like your POC, and release it as a new major version (come to think of it I'm not sure why this library is still on version 0.x). If this second option goes ahead would you like to be a maintainer of this repo too?

**Comment by bartveneman** [comment]
>  I think we will need to be driven by the decision in csstree/csstree#158

I agree on that 👍 

---

> If this second option goes ahead would you like to be a maintainer of this repo too?

I would consider it an honor. Many people and libraries depend on this library and it makes total sense to make the best possible version of this library to support as many people as possible.

**Comment by lahmatiy** [comment]
I intend to add specificity calculation function to CSSTree soon. Since it's hard to implement correctly and may be useful for other users. Actually, it's already implemented in CSSO as @bartveneman mentioned above. So it's mostly a moving implementation from CSSO to CSSTree with some tweaks. That's the question of time.

I also think about publishing various parts of CSSTree as separate packages in long term, like tokenizer, parser and so on. Specificity calculation would become a separate package as well. However, it may take some amount of time, since requires reorganisation of CSSTree repo and related things. But I think it's good to know for you about these plans.

The single thing I worry about is the library size. I do not know how critical this aspect would be for users, but I can say for sure that a size of specificity calculation based on CSSTree will be higher than the size of the current library. However, this is a price to pay for correctness and functionality. But so far these are only assumptions.

**Comment by bartveneman** [comment]
According to Bundlephobia:

------------------------------------
| Library | Minified size | Minzipped |
|--------|--------------|----------|
| [Specificity](https://bundlephobia.com/result?p=specificity@0.4.1) | 2.2kB | 494B |
| [CSSTree](https://bundlephobia.com/result?p=css-tree@1.1.3) | 380.7kB | 63.3kB |

That's quite the difference and that's without including the extra code we need to calculate specificity, sort specificity and explain the specificity per part of the selector.

> I also think about publishing various parts of CSSTree as separate packages in long term, like tokenizer, parser and so on. Specificity calculation would become a separate package as well.

This of course will hugely influnce the size but will most likely never be as small as Specificity currently is.

---

I'm not sure if I'd want to impose such a large package to *all* users of Specificity. But if @keeganstreet wants to make it a breaking change, than at least it becomes opt-in. Perhaps it would deserve a special note in the release notes.

@keeganstreet What do you say? 

1. Wait for it to be merged in CSSTree? 
2. Ask @lahmatiy if we can copy his CSSO implementation and use it here (@lahmatiy are you ok with that?)? 
3. Or skip the idea entirely?

For me no. 2 would work best and we can still try to make it backwards compatible so most people can benefit from the improved accuracy.

**Comment by lahmatiy** [comment]
@bartveneman Bundlephobia builds CSSTree by itself instead of using a bundle from the package (`dist` folder), it's wrongly add entire mdn/data into bundle. It will be [fixed](https://github.com/csstree/csstree/commit/06c4217a7fb5b3e94d2027c42072f81c89d751a0) in the next 1.x release. So CSSTree bundle size is actually about 167kB (minified). But it includes definition syntax dictionary (about 62kB) that's not needed for specificity as well as lexer, definition syntax utils, generator (including source map generator) etc. All is needed for specificity calculation is a parser that produces AST. The parser only bundle size is about 55kB minified (14kB gzipped) that is still much bigger than the Specificity library, but not so huge as in your table. I already made some work to [move CSSTree to ESM](https://github.com/csstree/csstree/tree/esm) in next major version and I expecting the size will be reduced more when bundled (it's already ~48kB, but there is still a room for improvements). However, as you mentioned, for sure it's never be as small as Specificity.

I intend to add specificity functions into CSSTree in a week or two. I also ok if you'll copy implementation from CSSO by your own (keep in mind, that it also requires CSSTree's AST to perform, so CSSTree parser will still be included).

**Comment by bartveneman** [comment]
Thanks, that's a very clear picture! I'll just wait until that's ready 😁

**Comment by timbomckay** [comment]
Any progress on this? I've been reviewing normalize/reset stylesheets and a significant amount of them are utilizing `:where()`. It's rather confusing coming to the css specificity calculator to see it not working. If it's not supported there should at least be an alert stating it's not supported.

**Comment by bartveneman** [comment]
Looks like @bramus did the work and implemented the CSSTree approach in a new library: https://github.com/bramus/js-specificity
