### ISSUE TITLE
The :is function breaks the tool when more than one argument is given

### ISSUE THREAD

**Issue by Pikamander2** [keeganstreet/specificity#48]
This CSS snippet works fine:

    .container > *:is(h1)

But this snippet breaks the tool:

    .container > *:is(h1, h2)

The first snippet reports `2 classes and 1 element` and its syntax gets correctly highlighted.

For the second snippet, the tool fails to highlight any part of the selector and instead reports a value of `0` for all three categories.

**Comment by keeganstreet** [comment]
Hey @Pikamander2 , sorry but I haven't added support for any level 4 CSS selectors, including the matches-any pseudo-class (`:is()`) https://www.w3.org/TR/selectors-4/#matches

**Comment by tarciozemel** [comment]
> Hey @Pikamander2 , sorry but I haven't added support for any level 4 CSS selectors, including the matches-any pseudo-class (`:is()`) https://www.w3.org/TR/selectors-4/#matches

Do you intend to?

**Comment by Inwerpsel** [comment]
The error is because of [this check](https://github.com/keeganstreet/specificity/blob/master/specificity.js#L176-L177) for a `,` anywhere in the selector.
A comma on the root level of the selector means there's (at least) 2 different specificities included, and the code wouldn't know which one you mean.

In case of the level 4 selectors the situation gets interesting.

Since **`is:()`** contributes to specificity, the code is really properly applying the same logic here. Multiple specificities are possible depending on which on which selector in the argument list applies to a given element, just like if the comma were at the root level. Perhaps the error message could be more explicit about this.

> Note: The specificity of the [:is()](https://www.w3.org/TR/selectors-4/#matches-pseudo) pseudo-class is replaced by the specificity of its most specific argument.

From https://www.w3.org/TR/selectors-4/#matches. Same goes for the `:not` selector.

Perhaps the code could try to catch the case where each part has identical specificity.

The **`:where()`** selector, on the other hand, by definition does not contribute to specificity. It should be possible to strip out each instance, and do a calculation on the remaining parts, right? If nothing is left the specificity is 0.
